spring:
  config:
    import: optional:classpath:.env

  application:
    name: sed

  datasource:
    url: ${DEFAULT_DB_URL}
    username: ${DEFAULT_DB_USERNAME}
    password: ${DEFAULT_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:     # ← spring 안으로 들어와야 함!
    hibernate:
      ddl-auto: update   # 또는 create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

file:
  directory: ${DEFAULT_FILE_DIRECTORY}