spring:
  config:
    import: optional:classpath:.env

  application:
    name: sed

  datasource:
    url: ${DEFAULT_DB_URL}
    username: ${DEFAULT_DB_USERNAME}
    password: ${DEFAULT_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: update   # none update create
  show-sql: true
  properties:
    hibernate:
      format_sql: true

server:
  port: 8080

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 150MB

file:
  directory: ${DEFAULT_FILE_DIRECTORY}